meta:
  engine: 4.1.0
  name: krypton
  version: alpha
  ref: &kb_ref "alpha release"
  author: mroetsc
  url: &kb_url github.com/mroetsc/krypton-kbd

units:
  # --- Proxy Spacing Variables --- #
  kx: U
  ky: U

  # --- Padding Variables --- #
  padding: 2
  px: kx + padding
  py: ky + padding

  # --- Other --- #
  stagger: 3
  splay: -3
  extra_spacing: 1
  thumbsplay: -6

  # --- Components --- #
  oled_width: 36
  oled_height: 14
  encoder_width: 12
  encoder_height: 12

points:
  zones:
    # ----- Keys ----- #
    matrix:
      anchor.shift: [125, -150]
      anchor.rotate: -3splay
      key:
        tags: [switch]
        #paddding: 1ky
        #spread: 1kx
        #height: 1ky
        #width: 1kx
      columns:
        stretch:
          rows.num.skip: true
          key.splay: splay
        pinky:
          key.splay: splay
          key.spread: 1px
        ring:
          key.stagger: stagger
          key.splay: splay
          key.spread: 1px
        middle:
          key.stagger: stagger
        index:
          key.stagger: -stagger
        inner:
          key.stagger: -stagger
        brackets:
          key.stagger: -stagger
          rows:
            bottom.skip: true
            top.skip: true
            num.skip: true
      rows:
        bottom:
        home:
        top:
        num:

    thumbfan:
      anchor:
        ref: matrix_index_bottom
        shift: [0, -1.25ky]
      columns:
        ctrl:
        super:
          key:
            splay: thumbsplay
            spread: 1px
            stagger: -0.5stagger
        space:
          key:
            splay: thumbsplay
            spread: 1px
            stagger: -0.5stagger
        layer:
          key:
            splay: thumbsplay
            spread: 1px
            stagger: -0.5stagger
      rows:
        cluster:

    oled:
      anchor:
        ref: matrix_inner_num
        shift: [2kx, 0.1ky]
      columns:
        display:
          key:
            tags: [oled]
            width: oled_width
            height: oled_height

    encoder:
      anchor:
        ref: matrix_inner_bottom
        shift: [45, -5]
      columns:
        encoder:
          key:
            tags: [encoder]
            width: encoder_width
            height: encoder_height

outlines:
  raw:
    - what: rectangle
      where: true
      bound: true
      size: [px, py]

  keys:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]

  board:
    - what: polygon
      operation: stack
      fillet: 3
      points:
        - ref: matrix_stretch_top
          shift: [-0.65px, 0.65py]
        - ref: matrix_stretch_top
          shift: [0.53px, 0.65py]
        - ref: matrix_pinky_num
          shift: [-0.65kx, 0.65py]
        - ref: matrix_middle_num
          shift: [0px, 0.65py]
        - ref: oled_display
          shift: [1.1px, 0.8py]
        - ref: thumbfan_layer_cluster
          shift: [1px, -0.65py]
        - ref: thumbfan_ctrl_cluster
          shift: [-0.6px, -0.65py]
        - ref: matrix_middle_bottom
          shift: [0.3px, -0.8py]
        - ref: matrix_stretch_bottom
          shift: [-0.65px, -0.65py]

  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  left:
    outlines:
      main:
        outline: board
    footprints:
      mx_hotswap:
        what: mx
        where: true
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
