meta:
  engine: 4.1.0
  name: krypton
  version: alpha
  ref: &kb_ref "alpha release"
  author: mroetsc
  url: &kb_url github.com/mroetsc/krypton-kbd

units:
  # --- Proxy Spacing Variables --- #
  kx: u
  ky: u

  # --- Padding Variables --- #
  padding: 2
  px: kx + padding
  py: ky + padding

  # --- Other --- #
  stagger: 3
  splay: -3
  extra_spacing: 1
  thumbsplay: -6

  # --- Components --- #
  oled_width: 36
  oled_height: 14
  encoder_width: 12
  encoder_height: 12

points:
  zones:
    # ----- Keys ----- #
    matrix:
      anchor:
        shift: [125, -150]
        rotate: -2splay
      key:
        tags: [switch]
        padding: 1ky
        spread: 1ky
      columns:
        stretch:
        pinky:
          key:
            stagger: stagger
            splay: splay
        ring:
          key:
            stagger: 2stagger
            splay: splay
        middle:
          key.stagger: stagger
        index:
          key.stagger: -stagger
        inner:
          key.stagger: -stagger
        brackets:
          key.stagger: -3stagger
          rows:
            bottom.skip: true
            top.skip: true
      rows:
        bottom:
        home:
        top:

    thumbs:
      anchor:
        ref: matrix_index_bottom
        shift: [0kx, -1.25ky]
      key:
        tags: [switch]
        padding: 1ky
        spread: 1ky
      columns:
        ctrl:
        super:
          key:
            splay: thumbsplay
            spread: 1px
            stagger: -0.5stagger
        space:
          key:
            splay: thumbsplay
            spread: 1px
            stagger: -0.5stagger
            height: 1.25ky
        layer:
          key:
            splay: thumbsplay
            spread: 1px
            stagger: -0.5stagger
      rows:
        cluster:

    encoder:
      anchor:
        ref: matrix_brackets_top
        shift: [0.25kx, 0.25ky]
      key:
        tags: [encoder]
        width: encoder_width
        height: encoder_height
      columns:

    oled:
      anchor:
        ref: matrix_brackets_bottom
        shift: [1.3kx, 0.8ky]
      key:
        tags: [encoder]
        width: oled_width
        height: oled_height
        rotate: 90

outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
