meta:
  engine: 4.1.0
  name: krypton
  version: alpha
  ref: &kb_ref "alpha release"
  author: mroetsc
  url: &kb_url github.com/mroetsc/krypton-kbd

units:
  # --- Proxy Spacing Variables --- #
  kx: u
  ky: u

  # --- Padding Variables --- #
  padding: 2
  px: kx + padding
  py: ky + padding

  # --- Other --- #
  stagger: 3
  splay: -3
  extra_spacing: 1
  thumbsplay: -6

  # --- Components --- #
  encoder_width: 12
  encoder_height: 12
  mcu_width: 18
  mcu_height: 33

points:
  zones:
    # ----- Keys ----- #
    matrix:
      anchor:
        shift: [125, -150]
        rotate: -2splay
      key:
        tags: [switch]
        padding: 1ky
        spread: 1ky
      columns:
        stretch:
          key:
            column_net: col1
          rows:
            num.skip: true
        pinky:
          key:
            stagger: stagger
            splay: splay
            column_net: col2
        ring:
          key:
            stagger: 2stagger
            splay: splay
            column_net: col3
        middle:
          key:
            stagger: stagger
            column_net: col4
        index:
          key:
            stagger: -stagger
            column_net: col5
        inner:
          key:
            stagger: -stagger
            column_net: col6
        brackets:
          key:
            stagger: -3stagger
            column_net: col7
          rows:
            bottom.skip: true
            top.skip: true
            num.skip: true
      rows:
        bottom:
          row_net: row4
        home:
          row_net: row3
        top:
          row_net: row2
        num:
          row_net: row1

    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [0.5kx, -1.35ky]
      key:
        tags: [switch]
        padding: 1ky
        spread: 1ky
      columns:
        super:
          key.column_net: col5
        space:
          key:
            splay: thumbsplay
            spread: 1.15kx
            stagger: -0.5stagger
            column_net: col6

        layer:
          key:
            splay: thumbsplay
            spread: 1.15kx
            stagger: -0.5stagger
            column_net: col7
      rows:
        cluster:
          row_net: row5

    encoder:
      anchor:
        ref: matrix_brackets_bottom
        shift: [1.5kx, 0.5ky]
      key:
        tags: [encoder]
        width: encoder_width
        height: encoder_height
      columns:
        encoder:
          key:
            column_net: col7
      rows:
        encoder:
          row_net: row3

    mcu:
      anchor:
        ref: matrix_brackets_top
        shift: [0.25kx, 1.5ky]
      key:
        tags: [mcu]
        width: mcu_width
        height: mcu_height

  #mirror:
  #  ref: matrix_brackets_top
  #  distance: 100

outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]

  keys:
    - what: rectangle
      where: switch
      bound: false
      size: [kx-0.5,ky-0.5]

  mcu:
    - what: rectangle
      where: mcu
      size: [mcu_width, mcu_height]

  encoder:
    - what: rectangle
      where: encoder
      size: [encoder_width, encoder_height]

  components:
    - name: components
    - operation: add
      name: keys
    - operation: add
      name: mcu
    - operation: add
      name: encoder

  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: thumb_layer_cluster
          shift: [1.34px, -0.5py]
        - ref: thumb_super_cluster
          shift: [-0.6px, -0.6py]
        - ref: matrix_index_bottom
          shift: [-0.15px, -0.75py]
        - ref: matrix_ring_bottom
          shift: [0px, -0.75py]
        - ref: matrix_pinky_bottom
          shift: [-0.75px, -0.85py]
        - ref: matrix_stretch_bottom
          shift: [-0.6px, -0.6py]
        - ref: matrix_stretch_top
          shift: [-0.6px, 0.6py]
        - ref: matrix_stretch_top
          shift: [0.4px, 0.6py]
        - ref: matrix_pinky_num
          shift: [-0.6px, 0.6py]
        - ref: matrix_ring_num
          shift: [-0.6px, 0.75py]
        - ref: matrix_middle_num
          shift: [0px, 0.6py]
        - ref: mcu
          shift: [0.6px, 0.85py]
        - ref: matrix_brackets_home
          shift: [0.85px, 0.5py]
        - ref: encoder_encoder_encoder
          shift: [0.6px, 0.75py]

  combo:
    - name: board
    - operation: subtract
      name: components

pcbs:
  left:
    outlines:
      main:
        outline: board
    footprints:
      mx_hotswap:
        what: ceoloide/switch_mx
        where: switch
        params:
          include_keycap: true
          reversible: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
          hotswap_3dmodel_filename: ${ERGOGEN_MODELS}/kali_hotswap.step
          hotswap_3dmodel_xyz_offset: [-0.7, -4.675, 1.75]
          hotswap_3dmodel_xyz_rotation: [180, 0, 180]
          switch_3dmodel_filename: ${ERGOGEN_MODELS}/mx_switch.step
          switch_3dmodel_xyz_offset: [0, 0, -6.5]
          switch_3dmodel_xyz_rotation: [0, -180, -90]
          keycap_3dmodel_filename: ${ERGOGEN_MODELS}/mx_keycap.step
          keycap_3dmodel_xyz_offset: [-8.75, 130.4, -13]
          keycap_3dmodel_xyz_rotation: [-180, 0, 0]

      diode:
        what: ceoloide/diode_tht_sod123
        where: switch
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: true
          diode_3dmodel_filename: ${KICAD9_3DMODEL_DIR}/Diode_THT.3dshapes/D_DO-35_SOD27_P7.62mm_Horizontal.step
          diode_3dmodel_xyz_offset: [-3.75, 0, 0]
        adjust:
          shift: [0, -5]

      nicenano:
        what: ceoloide/mcu_nice_nano
        where: mcu
        params:
          P3: RE_A
          P4: RE_C
          P5: row1
          P6: row2
          P7: row3
          P8: row4
          P9: row5
          P20: col1
          P19: col2
          P18: col3
          P15: col4
          P14: col5
          P16: col6
          P10: col7
          mcu_3dmodel_filename: ${ERGOGEN_MODELS}/mcu_nice_nano.step
          mcu_3dmodel_xyz_offset: [0, 0, 2.5]
          mcu_3dmodel_xyz_rotation: [0, 0, 90]

      reset:
        what: ceoloide/reset_switch_smd_side
        where:
          ref: mcu
          shift: [11, -25]
          rotate: -90
        params:
          reset_switch_3dmodel_filename: ${ERGOGEN_MODELS}/reset_switch.step
          reset_switch_3dmodel_xyz_rotation: [0, 0, 180]

      encoder:
        what: ceoloide/rotary_encoder_ec11_ec12
        where: encoder
        adjust:
          rotate: 180
        params:
          include_plate_hole_marking: true
          S1: col7
          S2: encoder_encoder
          encoder_3dmodel_filename: ${ERGOGEN_MODELS}/encoder.step

      diode_encoder:
        what: ceoloide/diode_tht_sod123
        where: encoder
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: true
          diode_3dmodel_filename: ${KICAD9_3DMODEL_DIR}/Diode_THT.3dshapes/D_DO-35_SOD27_P7.62mm_Horizontal.step
          diode_3dmodel_xyz_offset: [-3.75, 0, 0]
        adjust:
          shift: [0, -10]

      jstph:
        what: ceoloide/battery_connector_jst_ph_2
        where:
          ref: mcu
          shift: [0, -22.5]
        params:
          side: B
          battery_connector_3dmodel_filename: ${ERGOGEN_MODELS}/jst_connector.step
          battery_connector_3dmodel_xyz_offset: [-1, 0, 0]
          battery_connector_3dmodel_xyz_rotation: [180, 0, 0]

      power:
        what: ceoloide/power_switch_smd_side
        where:
          ref: encoder_encoder_encoder
          shift: [0, 16]
          rotate: 80
        params:
          switch_3dmodel_filename: ${ERGOGEN_MODELS}/power_switch.stp
          switch_3dmodel_xyz_rotation: [-90, 0, -90]
