meta:
  engine: 4.1.0
  name: krypton
  version: alpha
  ref: &kb_ref "alpha release"
  author: mroetsc
  url: &kb_url github.com/mroetsc/krypton-kbd

units:
  # --- Proxy Spacing Variables --- #
  kx: u
  ky: u

  # --- Padding Variables --- #
  padding: 2
  px: kx + padding
  py: ky + padding

  # --- Other --- #
  stagger: 3
  splay: -3
  extra_spacing: 1
  thumbsplay: -6

  # --- Components --- #
  encoder_width: 12
  encoder_height: 12
  mcu_width: 18
  mcu_height: 33

points:
  zones:
    # ----- Keys ----- #
    matrix:
      anchor:
        shift: [125, -150]
        rotate: -2splay
      key:
        tags: [switch]
        padding: 1ky
        spread: 1ky
      columns:
        stretch:
          rows:
            num.skip: true
        pinky:
          key:
            stagger: stagger
            splay: splay
        ring:
          key:
            stagger: 2stagger
            splay: splay
        middle:
          key.stagger: stagger
        index:
          key.stagger: -stagger
        inner:
          key.stagger: -stagger
        brackets:
          key.stagger: -3stagger
          rows:
            bottom.skip: true
            top.skip: true
            num.skip: true
      rows:
        bottom:
        home:
        top:
        num:

    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [0.5kx, -1.35ky]
      key:
        tags: [switch]
        padding: 1ky
        spread: 1ky
      columns:
        super:

        space:
          key:
            splay: thumbsplay
            spread: 1px
            stagger: -0.5stagger

        layer:
          key:
            splay: thumbsplay
            spread: 1px
            stagger: -0.5stagger
      rows:
        cluster:

    encoder:
      anchor:
        ref: matrix_brackets_bottom
        shift: [1.5kx, 0.5ky]
      key:
        tags: [encoder]
        width: encoder_width
        height: encoder_height
      columns:
        encoder:
      rows:
        encoder:

    mcu:
      anchor:
        ref: matrix_brackets_top
        shift: [0.25kx, 1.4ky]
      key:
        tags: [mcu]
        width: mcu_width
        height: mcu_height

outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: thumb_layer_cluster
          shift: [0, 0]
