meta:
  engine: 4.1.0
  name: krypton
  version: alpha
  ref: &kb_ref "alpha release"
  author: mroetsc
  url: &kb_url github.com/mroetsc/krypton-kbd

units:
  # --- Proxy Spacing Variables --- #
  kx: u
  ky: u

  switch_cutout: 14
  # TODO: encoder_cutout: 
  screw_diameter: 2.2

  # --- Padding Variables --- #
  padding: 2
  px: kx + padding
  py: ky + padding
  dpx: px + 2 * padding
  dpy: py + 2 * padding

  # --- Other --- #
  stagger: 3
  splay: -3
  extra_spacing: 1
  thumbsplay: -23

  # --- Components --- #
  encoder_width: 12
  encoder_height: 12
  mcu_width: 18
  mcu_height: 33
  display_height: 36
  display_width: 14

points:
  zones:
    # ----- Keys ----- #
    matrix:
      anchor:
        shift: [125, -150]
        rotate: -2splay
      key:
        tags: [switch]
        padding: 1ky
        spread: 1kx
      columns:
        stretch:
          key:
            column_net: col1
          rows:
            num.skip: true
        pinky:
          key:
            stagger: stagger
            spread: 1.05ky
            splay: splay
            column_net: col2
        ring:
          key:
            stagger: 2stagger
            spread: 1.05ky
            splay: splay
            column_net: col3
        middle:
          key:
            stagger: stagger
            column_net: col4
        index:
          key:
            stagger: -stagger
            column_net: col5
        inner:
          key:
            stagger: -stagger
            column_net: col6
        brackets:
          key:
            stagger: -3stagger
            column_net: col7
          rows:
            bottom.skip: true
            top.skip: true
            num.skip: true
      rows:
        bottom:
          row_net: row4
        home:
          row_net: row3
        top:
          row_net: row2
        num:
          row_net: row1

    thumb:
      anchor:
        ref: matrix_index_bottom
        shift: [0.5kx, -1.35ky]
      key:
        tags: [switch]
        padding: 1ky
        spread: 1ky
      columns:
        super:
          key:
            column_net: col5
        space:
          key:
            splay: thumbsplay
            spread: 1.25kx
            stagger: -1.5stagger
            column_net: col6

        layer:
          key:
            splay: thumbsplay
            spread: 1.25kx
            stagger: -1.5stagger
            column_net: col7
      rows:
        cluster:
          row_net: row5

    encoder:
      anchor:
        ref: matrix_brackets_bottom
        shift: [0.9kx, -0.2ky]
      key:
        tags: [encoder]
        width: encoder_width
        height: encoder_height
      columns:
        encoder:
          key:
            column_net: col7
      rows:
        encoder:
          row_net: row3

    mcu:
      anchor:
        ref: matrix_brackets_top
        shift: [0.25kx, 1.55ky]
      key:
        tags: [mcu]
        width: mcu_width
        height: mcu_height

    display:
      anchor:
        ref: mcu
        shift: [0, -0.15py]
      key:
        tags: [display]
        width: display_width
        height: display_height

  #mirror:
  #  ref: matrix_brackets_top
  #  distance: 100

outlines:
  _keys:
    - what: rectangle
      where: switch
      bound: false
      size: [switch_cutout, switch_cutout]

  _mcu:
    - what: rectangle
      where: mcu
      size: [mcu_width, mcu_height]

  _display:
    - what: rectangle
      where: display
      size: [display_width, display_height]

  _encoder:
    - what: rectangle
      where: encoder
      size: [encoder_width, encoder_height]

  _components:
    - name: _components
    - operation: add
      name: _keys
    - operation: add
      name: _mcu
    - operation: add
      name: _display
    - operation: add
      name: _encoder

  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: encoder_encoder_encoder
          shift: [0.65px, -1.4py]
        - ref: encoder_encoder_encoder
          shift: [-0.1px, -2.15py]
        - ref: matrix_brackets_home
          shift: [0.0px, -2.5py]
        - ref: thumb_super_cluster
          shift: [0.5px, -0.6py]
        - ref: thumb_super_cluster
          shift: [-0.6px, -0.6py]
        - ref: matrix_index_bottom
          shift: [-0.15px, -0.7py]
        - ref: matrix_ring_bottom
          shift: [-0.1px, -0.7py]
        - ref: matrix_pinky_bottom
          shift: [0.3px, -0.92py]
        - ref: matrix_stretch_bottom
          shift: [-0.6px, -0.6py]
        - ref: matrix_stretch_top
          shift: [-0.6px, 0.6py]
        - ref: matrix_stretch_top
          shift: [0.47px, 0.6py]
        - ref: matrix_pinky_num
          shift: [-0.6px, 0.6py]
        - ref: matrix_pinky_num
          shift: [0.51px, 0.6py]
        - ref: matrix_ring_num
          shift: [-0.6px, 0.75py]
        - ref: mcu
          shift: [0.625px, 0.82py]
        - ref: matrix_brackets_home
          shift: [0.85px, 0py]
        - ref: encoder_encoder_encoder
          shift: [0.65px, 0.68py]

  combo:
    - name: board
    - operation: subtract
      name: _components

  _holeTopLeft:
    - what: circle
      radius: screw_diameter / 2
      where:
        ref: matrix_ring_top
        shift: [-9.5, 9.5]
  _holeBottomLeft:
    - what: circle
      radius: screw_diameter / 2
      where:
        ref: matrix_ring_bottom
        shift: [-9.5, 9.5]
  _holeTopRight:
    - what: circle
      radius: screw_diameter / 2
      where:
        ref: matrix_inner_top
        shift: [-9.5, 11]
  _holeBottomRight:
    - what: circle
      radius: screw_diameter / 2
      where:
        ref: matrix_inner_bottom
        shift: [-9.5, 11]
  _holeOuterRight:
    - what: circle
      radius: screw_diameter / 2
      where:
        ref: encoder_encoder_encoder
        shift: [7, -15]

  _holes:
    - name: _holeTopLeft
    - operation: add
      name: _holeBottomLeft
    - operation: add
      name: _holeTopRight
    - operation: add
      name: _holeBottomRight
    - operation: add
      name: _holeOuterRight

  _switchplate:
    - name: board
    - operation: subtract
      name: _keys
    - operation: subtract
      name: _encoder
    - operation: subtract
      name: _holes

pcbs:
  left:
    outlines:
      main:
        outline: board
    footprints:
      mx_hotswap:
        what: ceoloide/switch_mx
        where: switch
        params:
          include_keycap: true
          reversible: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
          hotswap_3dmodel_filename: ${ERGOGEN_MODELS}/kali_hotswap.step
          hotswap_3dmodel_xyz_offset: [-0.7, -4.675, 1.75]
          hotswap_3dmodel_xyz_rotation: [180, 0, 180]
          switch_3dmodel_filename: ${ERGOGEN_MODELS}/mx_switch.step
          switch_3dmodel_xyz_offset: [0, 0, -6.5]
          switch_3dmodel_xyz_rotation: [0, -180, -90]
          keycap_3dmodel_filename: ${ERGOGEN_MODELS}/mx_keycap.step
          keycap_3dmodel_xyz_offset: [-8.75, 130.4, -13]
          keycap_3dmodel_xyz_rotation: [-180, 0, 0]

      diode:
        what: ceoloide/diode_tht_sod123
        where: switch
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: true
          diode_3dmodel_filename: ${KICAD9_3DMODEL_DIR}/Diode_THT.3dshapes/D_DO-35_SOD27_P7.62mm_Horizontal.step
          diode_3dmodel_xyz_offset: [-3.75, 0, 0]
        adjust:
          shift: [0, -5]

      nicenano:
        what: ceoloide/mcu_nice_nano
        where: mcu
        params:
          P1: CS
          P2: SCL
          P3: MOSI
          P21: RE_A
          P4: RE_C
          P5: row1
          P6: row2
          P7: row3
          P8: row4
          P9: row5
          P20: col1
          P19: col2
          P18: col3
          P15: col4
          P14: col5
          P16: col6
          P10: col7
          mcu_3dmodel_filename: ${ERGOGEN_MODELS}/mcu_nice_nano.step
          mcu_3dmodel_xyz_offset: [0, 0, 2.5]
          mcu_3dmodel_xyz_rotation: [0, 0, 90]

      niceview:
        what: ceoloide/display_nice_view
        where: display
        params:
          SCK: SCL
          niceview_3dmodel_filename: ${ERGOGEN_MODELS}/nice_view.step
          niceview_3dmodel_xyz_offset: [0, 0, 8]
          niceview_3dmodel_xyz_rotation: [0, 0, -90]

      reset:
        what: ceoloide/reset_switch_smd_side
        where:
          ref: matrix_inner_num
          shift: [-5, 16.5]
        params:
          reset_switch_3dmodel_filename: ${ERGOGEN_MODELS}/reset_switch.step
          reset_switch_3dmodel_xyz_rotation: [0, 0, 180]

      encoder:
        what: ceoloide/rotary_encoder_ec11_ec12
        where: encoder
        adjust:
          rotate: 180
        params:
          include_plate_hole_marking: true
          S1: col7
          S2: encoder_encoder
          encoder_3dmodel_filename: ${ERGOGEN_MODELS}/encoder_with_knob.step

      diode_encoder:
        what: ceoloide/diode_tht_sod123
        where: encoder
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: true
          diode_3dmodel_filename: ${KICAD9_3DMODEL_DIR}/Diode_THT.3dshapes/D_DO-35_SOD27_P7.62mm_Horizontal.step
          diode_3dmodel_xyz_offset: [-3.75, 0, 0]
        adjust:
          shift: [0, -10]

      jstph:
        what: ceoloide/battery_connector_jst_ph_2
        where: mcu
        adjust:
          shift: [-12, -35.5]
          rotate: 90
        params:
          side: B
          battery_connector_3dmodel_filename: ${ERGOGEN_MODELS}/jst_connector.step
          battery_connector_3dmodel_xyz_offset: [-1, 0, 0]
          battery_connector_3dmodel_xyz_rotation: [180, 0, 0]

      power:
        what: ceoloide/power_switch_smd_side
        where:
          ref: matrix_inner_num
          shift: [8, 16.75]
          rotate: 90
        params:
          switch_3dmodel_filename: ${ERGOGEN_MODELS}/power_switch.stp
          switch_3dmodel_xyz_rotation: [-90, 0, -90]

      holeTopLeft:
        what: ceoloide/mounting_hole_plated
        where:
          ref: matrix_ring_top
          shift: [-9.5, 9.5]
      holeBottomLeft:
        what: ceoloide/mounting_hole_plated
        where:
          ref: matrix_ring_bottom
          shift: [-9.5, 9.5]
      holeTopRight:
        what: ceoloide/mounting_hole_plated
        where:
          ref: matrix_inner_top
          shift: [-9.5, 11]
      holeBottomRight:
        what: ceoloide/mounting_hole_plated
        where:
          ref: matrix_inner_bottom
          shift: [-9.5, 11]
      holeOuterRight:
        what: ceoloide/mounting_hole_plated
        where:
          ref: encoder_encoder_encoder
          shift: [8, -15]

cases:
  bottom:
    - name: board
      extrude: 1
    - operation: subtract
      name: _holes

  switchplate:
    - name: _switchplate
      extrude: 1
